version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.1
    restart: always
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

  kibana:
    #image: docker.elastic.co/kibana/kibana:6.2.1
    build: ./kibana
    ports:
      - "5601:5601"
    restart: always
    networks:
      default:
      public:
          ipv4_address: 99.40.229.34
    cap_add:
      - NET_ADMIN
    environment:
      - DEFAULT_GW=99.40.229.38

  ghtoes:
    build: ./ghtoes
    restart: always
    environment:
      - GITHUB_TOKEN=TOKEN_HERE

volumes:
  elasticsearch:

networks:
  public:
    external: true
